services:
  localstack:
    image: localstack/localstack:2.0.2 
    ports:
      - 4566:4566
    volumes:
      - "./output/:/var/lib/localstack/app/local"
      - "./localstack/setup.sh:/etc/localstack/init/ready.d/init-aws.sh"
